### PR TITLE
feat: Added badge in README file

### PR DESCRIPTION
**Pull request by DevKumar00001**

### CODE REVIEW

**Comment by PranavPurwar** [comment]
For the CI badge, its no use since GitHub already shows that besides commit name

**Comment by DevKumar00001** [comment]
> And other badges should link to the respective pages like for contributors and commits

I have not changed anything in old badge.

**Comment by JavkhlanK** [comment]
i don't really see the need for that CI or repository size badge, but that downloads one seems neat

**Comment by DevKumar00001** [comment]
> i don't really see the need for that CI or repository size badge, but that downloads one seems neat

Repo size badge is not bad.For first time when I cloned this repository I was unknown how much repository size is with `.git`  dir.

**Pull request merged**
