### PR TITLE
Latest Official Android Jar SDK 33

### PR DESCRIPTION
**Pull request by arab-ware**
This android jar is the latest one from official android build tools , it has been tested on latest sketchware pro and it does not contain any problem You can merge it or no (download it yourself)

### CODE REVIEW

**Comment by Arashvscode** [comment]
> This android jar is the latest one from official android build tools , it has been tested on latest sketchware pro and it does not contain any problem You can merge it or no (download it yourself)


This file doesn't seem safe because I tested it and it didn't run on my project. Wait for jbk0 to update Android.jar. Some of these files may contain malicious codes.

**Comment by arab-ware** [comment]
> > This android jar is the latest one from official android build tools , it has been tested on latest sketchware pro and it does not contain any problem You can merge it or no (download it yourself)
> 
> This file doesn't seem safe because I tested it and it didn't run on my project. Wait for jbk0 to update Android.jar. Some of these files may contain malicious codes.

I don't understand why talk like this on every thing I comment (issue or pull request)

I don't understand you even 

First , this is FROM OFFICIAL SITE so how it contains a virus lol

Second , it does not add any thing in the app codes , it is just JAR MY FRIEND....NOT A DEX


THIRD ,WORKING PERFECTLY FOR 04RC tested and complied mu android 13 projects

**Comment by JavkhlanK** [comment]
I don't particularly trust binaries like JARs or ZIP archives, sorry. I'll also do it myself to add where I got the JAR from to the commit message.  
Nonetheless, thank you for your contributions!

**Comment by PranavPurwar** [comment]
what android.jar is just a stub, even if you inject some malicious code, it's not gonna ever execute it lmao

**Comment by Arashvscode** [comment]
> 

My dear Bro, Android Studio itself provides you with an Android.jar file when it installs the SDK

**Comment by PranavPurwar** [comment]
but we're talking about sketchware pro and not AS and btw, you can just check SHA to make sure that it was not edited

**Pull request closed without merging**
