### PR TITLE
Resolve issue with drag and drop

### PR DESCRIPTION
**Pull request by elfilibusterismo**
This pr is supposed to solve this issue https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1219

However, this changes need more testing.

### CODE REVIEW

**Comment by PranavPurwar** [comment]
"needs more testing"
Ilyasse: lets merge it rn

**Comment by ilyassesalama** [comment]
> "needs more testing" Ilyasse: lets merge it rn

IMG_0011

**Comment by PranavPurwar** [comment]
It works for some doesn't mean it will work for everyone, thats why PRs are thoroughly tested before merging rather than on user feedback alone.

**Comment by elfilibusterismo** [comment]
> It works for some doesn't mean it will work for everyone, thats why PRs are thoroughly tested before merging rather than on user feedback alone.

Actually the "some" you're talking about is the ones who experiencing the issue

**Comment by PranavPurwar** [comment]
> > It works for some doesn't mean it will work for everyone, thats why PRs are thoroughly tested before merging rather than on user feedback alone.
> 
> Actually the "some" you're talking about is the ones who experiencing the issue

Yes, but what if it causes some unexpected behaviour? What if it breaks backwards compatibility? That's why I think its necessary to thoroughly test it. especially because it deals with legacy code.

**Pull request merged**
