### PR TITLE
New local libraries look

### PR DESCRIPTION
**Pull request by aikrq**
Also it have one fix of MenuItem state.

### CODE REVIEW

**Comment by ilyassesalama** [comment]
A screenshot of the change would be great.

**Comment by aikrq** [comment]
> A screenshot of the change would be great.

Of course.
Screenshot1

Screenshot2

**Comment by ilyassesalama** [comment]
The UI looks awesome, but is it really good to give up on the activity title?

**Comment by aikrq** [comment]
> The UI looks awesome, but is it really good to give up on the activity title?

What do you mean?

**Comment by hasrat-ali** [comment]
Everything looks good but can you fix this first?


https://github.com/user-attachments/assets/4112050c-fac2-4ee5-8dab-8012e8494a60

**Comment by aikrq** [comment]
> Everything looks good but can you fix this first?
> 
> 
> https://github.com/user-attachments/assets/4112050c-fac2-4ee5-8dab-8012e8494a60
> 
> 

Lmao, idk for some reason I can't reproduce this.

**Pull request closed without merging**
