### PR TITLE
fix: Crash when use res values in ```Custom Attributes```

### PR DESCRIPTION
**Pull request by trindadedev13**
this does not add support for res values, but causes sketchware to crash, I even started trying to make support for res values, but stopped

### CODE REVIEW

**Comment by trindadedev13** [comment]
> Can you tell me how can I reproduce this crash?

app:cornerRadius="@dimen/some_dimen"

use this on a button, and you will crash.

**Comment by trindadedev13** [comment]
> > Can you tell me how can I reproduce this crash?
> 
> app:cornerRadius="@dimen/some_dimen"
> 
> use this on a button, and you will crash.

and no, it doesn't only happen with this code, it happens with any code that is being used in the preview that uses something from res instead of the direct value

**Comment by elfilibusterismo** [comment]
Modifying PropertiesUtil#resolveSize to handle that would be easier

**Comment by trindadedev13** [comment]
> Modifying PropertiesUtil#resolveSize to handle that would be easier

Yesss really, I hadn't thought of that

**Comment by trindadedev13** [comment]
closing because I probably won't finish

**Comment by ilyassesalama** [comment]
Pensive

**Comment by Mester-Dark** [comment]
Oh Sorry ...

**Comment by trindadedev13** [comment]
what

**Pull request closed without merging**
