### PR TITLE
feat: Add Pseudo Logcat Reader

### PR DESCRIPTION
**Pull request by khaled-0**
This PR adds a full fledged ```Logcat Reader``` and Functionality for All(Hopefully) Log Related Stuffs in The Projects Made With.
To enable logcat support in your apps, enable Logcat Option from build settings.
**Make sure you don't keep it enabled in the final builds unless you know what you're doing**

Function Wise (if Logcat Enabled)
Made projects will include a class ```SketchLogger.java```
This Class Uses ```java.lang.Process``` to execute and read each and every (hopefully) logs from the app itself. Then using a BuffereredReader, it Broadcasts the logs one by one with an intent filter ```RECEIVE_NUB_LOGS``` which than gets picked by Sketchware.
Also in order for that ```SketchLogger.java``` class to work one must call ```SketchLogger.startLogging(Context)``` from somewhere in the app. It's usually done automatically in ```SketchApplication.java``` but if for some reason user doesn't use the default application class they must use that method in order for the logcat to work.
**More info can be found in the class itself***

As for Reading The broadcast , Open the ```Logcat Reader``` from Design Menu in Sketchware Pro before opening the application. So you won't miss out the logs of app startup.

Finally. I don't know what else to write anymore.🙏🙏

### CODE REVIEW

**Review by JavkhlanK — DISMISSED** [review]

**Comment by JavkhlanK** [comment]
Why's this PR marked as WIP btw?

**Comment by khaled-0** [comment]
i haven't checked the updated DesignDrawer while resolving conflicts. please kindly test that out when you can, should work tho

**Comment by khaled-0** [comment]
These commits are a mess ngl 😔

**Comment by khaled-0** [comment]
cleaned most of messy commits as much as I could.

**Pull request merged**
