### PR TITLE
feat : Improvements to SketchApplication.java

### PR DESCRIPTION
**Pull request by Yamenher**
Removed `AlarmManger` component and used directly `Intent` component for redirecting to `CollectErrorActivity` to make unhandled errors catching more responsive in newer Android versions

### CODE REVIEW

**Comment by ilyassesalama** [comment]
Duplicate of #1148. This is your 3rd pull request with the same change. You should stop.

**Comment by Yamenher** [comment]
> Duplicate of #1148. This is your 3rd pull request with the same change. You should Check telegram msgs an reopen my pr now

**Comment by Yamenher** [comment]
> Duplicate of #1148. This is your 3rd pull request with the same change. You should stop.

Stop that an reopen my pr
GO check out the telegram msgs in Contributions section

**Comment by Yamenher** [comment]
> Duplicate of #1148. This is your 3rd pull request with the same change. You should stop.

Hey @ilyassesalama why ingnoring my messages??

**Pull request closed without merging**
