### PR TITLE
Updated libs and added constraintlayout solver to qq.java

### PR DESCRIPTION
**Pull request by Wall-Hub2**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Hi, I haven't forgot about this one! I still have to check what's been changed and test them out

**Comment by DantaNotEpic** [comment]
<a:fastsad:816072729148260353> :pray:

**Comment by JavkhlanK** [comment]
bruh

**Comment by DantaNotEpic** [comment]
pro

**Comment by Wall-Hub2** [comment]
@JavkhlanK 
imma make a new pull request with new changes

**Comment by JavkhlanK** [comment]
ok

**Pull request closed without merging**
