### PR TITLE
feat : migrate some classes to use Resources

### PR DESCRIPTION
**Pull request by AlucardTN**
sorry about ViewPane class, i already changed to LF and did CTRL +ALT + R

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Have you tested your changes out?

**Comment by JavkhlanK** [comment]
And why did you delete many constants inside Resources.java?

**Comment by AlucardTN** [comment]
yes tested
i didn't deleted anything from resources class, it's outdated means not the
last one from your repo

**Comment by JavkhlanK** [comment]
Please fix the file to include newer Resource IDs.

**Pull request closed without merging**
