### PR TITLE
better version of #273

### PR DESCRIPTION
**Pull request by PranavPurwar**

### CODE REVIEW

**Comment by PranavPurwar** [comment]
DO NOT SAY THAT COPYING LIBS TO EXTERNAL STORAGE IS UNNECESSARY, BECAUSE IF I DON'T THEN THE APP WILL CONTAIN THEM AS "MULTIDEX-XXX.DEX" WHICH WILL CRASH THE APK

**Comment by tyron12233** [comment]
whats with the all caps

**Comment by PranavPurwar** [comment]
NOTHING

**Comment by PranavPurwar** [comment]
merge this and release beta 7 when

**Comment by PranavPurwar** [comment]
another tip: use Incremental compilation from {@package mod.tyron.compiler} before releasing next beta

**Comment by JavkhlanK** [comment]
Behavior like "screaming" with caps lock on is not welcome here. The same applies to the attitude you have, especially when phrased like "Don't say that […] because if I don't […]". Since you already got warned before, measures will be taken in an appropriate manner.

Please stop being this toxic, or else, you will be banned permanently from collaborating in this repository.

**Pull request closed without merging**
