### PR TITLE
Fix and Feat

### PR DESCRIPTION
**Pull request by elfilibusterismo**
Fix : YouTubePlayerView
by updating kotlin stdlib to 1.6.0

### CODE REVIEW

**Comment by JavkhlanK** [comment]
1. Please keep different changes/fixes in different Pull requests. Closing #803 just to include its changes in here was a bad decision. What if #803's original changes are ready to be merged, but the new ones you added here not? All changes would have to wait before they can be merged.
2. Also don't comment *the same message in three different Issues, some of them even closed*, that's spam. If you really want to reference them in your Pull request, add something like this to its description: "Fixes #401, #780, #807". Better to only mention the open Issue though, the others are duplicates of it.
3. When modifying built-in libraries, at least also tell *what you did to fix the issue*. We need to also be able to reproduce the .dex file(s) you compiled, otherwise we can't be sure if it contains malicious code or not.
4. I hope this is redundant to mention, but I'll have a look at this PR when I've got the time.

**Comment by elfilibusterismo** [comment]
Oh, yah. Forgot to tell. I updated the kotlin stdlib to 1.6.0 and stdlib-jdk7 to 1.6.0 I still used the old name "kotlin-stdlib-1.4.30-M1-release-152" same with jdk7. I still used the the same name because if i changed the name to 1.6.0 I'm worried to it may cause a conflict on other feature because it uses the kotlin-stdlib-1.4.30-M1-release-152 name. Like exclude Library feature.

**Comment by elfilibusterismo** [comment]
Sorry this is my first time. I just ask TechnicalStudioDeveloper to help me commit and make a pull request.

**Comment by JavkhlanK** [comment]
`org.jetbrains.kotlin:kotlin-stdlib:1.6.0` seems to depend on `org.jetbrains.kotlin:kotlin-stdlib-common:1.6.0` which wasn't added as built-in library. This PR seems incomplete, but I might fix it when I've got the time.

**Comment by JavkhlanK** [comment]
This PR did make my test project using a YouTube Player View work after pressing on Run though! Nice!

**Comment by JavkhlanK** [comment]
wha

**Pull request closed without merging**
