### PR TITLE
Some Improvements

### PR DESCRIPTION
**Pull request by Edward-NewGate-KOC**

### CODE REVIEW

**Comment by ilyassesalama** [comment]
Pranav already rewrote `Fx` class in #1339. I don't it's useful in this PR now.

**Comment by Edward-NewGate-KOC** [comment]
> Pranav already rewrote `Fx` class in #1339. I don't think it's useful in this PR now.

The `Fx` class was indeed taken from `Pravav’s PR`, but I need it to generate the blocks code correctly ( it's better than using `builtInBlocks method` ). If we go back to the old method, the error I explained will return, and we’ll completely lose the quick access feature to the StringEditor from the blocks palettes.

**Comment by Edward-NewGate-KOC** [comment]
> Pranav already rewrote `Fx` class in #1339. I don't think it's useful in this PR now.

bro, please check the last commit to know exactly why I need `a.a.a.Fx`

**Comment by PranavPurwar** [comment]
You can add the blocks like how lightStatusBar block is added and does not use Fx for code generation

**Comment by Edward-NewGate-KOC** [comment]
Now, everything’s working perfectly 🙂

**Pull request merged**
