### PR TITLE
Feat: Added Dialog before exit and Save option

### PR DESCRIPTION
**Pull request by BlueCatSoftware**
Codes are fixed now and working fine for

### CODE REVIEW

**Comment by hasrat-ali** [comment]
Did you test your changes as well?
There is duplicate methods.

https://github.com/Sketchware-Pro/Sketchware-Pro/blob/cf7491010969300493a1da1b3ad52731a8c4936a/app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java#L133

https://github.com/Sketchware-Pro/Sketchware-Pro/blob/cf7491010969300493a1da1b3ad52731a8c4936a/app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java#L157

**Comment by JavkhlanK** [comment]
if your code isn't done yet, why did you open a PR already?

**Comment by BlueCatSoftware** [comment]
> if your code isn't done yet, why did you open a PR already?
I contributed through mobile.  I don't really know how to save all what I done without hitting the PR i hope you understand.

**Comment by hasrat-ali** [comment]
> > I contributed through mobile.  I don't really know how to save all what I done without hitting the PR i hope you understand.

Just commit to your fork

**Comment by BlueCatSoftware** [comment]
> Did you test your changes as well?
> There is duplicate methods.
> 
> https://github.com/Sketchware-Pro/Sketchware-Pro/blob/cf7491010969300493a1da1b3ad52731a8c4936a/app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java#L133
> 
> https://github.com/Sketchware-Pro/Sketchware-Pro/blob/cf7491010969300493a1da1b3ad52731a8c4936a/app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java#L157
Editing on mobile is uncomfortable

**Comment by BlueCatSoftware** [comment]
> > > I contributed through mobile.  I don't really know how to save all what I done without hitting the PR i hope you understand.
> 
> Just commit to your fork

Okay okay

**Comment by Iyxan23** [comment]
or open a draft pull request instead (I think you can convert a pull request to a draft pull request) 

image

**Comment by RealNethical** [comment]
Ngl actually if u click on the three dots of ur chrome browser theres a option to open the site in desktop mode . So then u can fork the repo and edit it ⊂(◉‿◉)つ

**Comment by BlueCatSoftware** [comment]
> or open a draft pull request instead (I think you can convert a pull request to a draft pull request) 
> 
> image

Yeah thanks

**Comment by JavkhlanK** [comment]
I'm not sure what the bluecat file does or is there for.

**Review by khaled-0 — COMMENTED** [review]
What's this file for?

**Comment by BlueCatSoftware** [comment]
> I'm not sure what the bluecat file does or is there for.

Ask before exit, cos some users might mistakenly press back without saving changes or progress

**Comment by khaled-0** [comment]
> > I'm not sure what the bluecat file does or is there for.
> 
> Ask before exit, cos some users might mistakenly press back without saving changes or progress

Yea that's cool n all.
But what does the file 'bluecat' in root dir with nothing in it supposed to do.

**Comment by Sajid-Kabir** [comment]
What's That?

**Pull request closed without merging**
