### PR TITLE
Update BlocksManagerCreatorActivity.java

### PR DESCRIPTION
**Pull request by BlueCatSoftware**
feat: Added Syntax Highlighter to the edittext.

### CODE REVIEW

**Comment by hasrat-ali** [comment]
You have wrong `import` statement.
https://github.com/Sketchware-Pro/Sketchware-Pro/blob/c012558cf060c64e170fb442aff7b7ac8e146c0d/app/src/main/java/mod/hilal/saif/activities/tools/BlocksManagerCreatorActivity.java#L43
Instead of
```java
import mod.w3wide.highlighter.SimpleHighlighter;
```

**Comment by JavkhlanK** [comment]
and that single `_setHighlighter` method seems kinda nub ngl

**Comment by BlueCatSoftware** [comment]
> ```java
> .
> ```

Oops I'm was clumsy.

**Comment by BlueCatSoftware** [comment]
> and that single `_setHighlighter` method seems kinda nub ngl
Change it

**Pull request merged**
