### PR TITLE
style:Use fullscreen for some AlertDialog(s)

### PR DESCRIPTION
**Pull request by khaled-0**
AlertDialog for viewing single source code is now using a fullscreen theme. 
Namely ```android.R.style.Theme_DeviceDefault_Light_NoActionBar```
a built in theme because I don't feel like creating a new custom theme.

I will be adding this style to as much AlertDialog possible without breaking anything.

### CODE REVIEW

**Comment by khaled-0** [comment]
Review now bor

**Comment by JavkhlanK** [comment]
I'm honestly not sure if it'll look great, the design now heavily depends on device manufacturer/OS skin

**Comment by khaled-0** [comment]
It looks fine. Nothing Changes noticably

**Comment by JavkhlanK** [comment]
Just tested that out and it's weird, making the dialog fullscreen didn't change much and looks off without a proper transition in my opinion.

**Comment by khaled-0** [comment]
Guess I'll try to make custom style

**Pull request closed without merging**
