### PR TITLE
Update zipalign-java

### PR DESCRIPTION
**Pull request by Iyxan23**
This pull request updates the zipalign-java jar to the current latest commit of `Iyxan23/zipalign-java` at `96fd6b30c928015847264b27b0d2dd407f3e8895`. It also updates Sketchware Pro to use the faster method.

Aligning zip is now considerably faster than it previously was.

Using the previous sketchware pro version, aligning a ~187KiB apk takes about `3494ms`. This new update cuts down that time to just only `684ms`.

### CODE REVIEW

**Comment by 17606657524** [comment]
Flash back

**Comment by 17606657524** [comment]
On the mobile phone, I use the flash back version.

**Comment by Iyxan23** [comment]
The build is crashing due to the latest commit being buggy, please use this build instead that's based off of the latest rc with the same update commits applied: https://github.com/Iyxan23/Sketchware-Pro/actions/runs/2384429111

**Comment by Iyxan23** [comment]
sigh, could've used the `zipalign-update` branch as the incoming branch instead

**Comment by anthony-china** [comment]
ok

**Comment by anthony-china** [comment]
We look forward to optimizing the packaging speed

**Pull request merged**
