### PR TITLE
feat: Can use unknow variable easier

### PR DESCRIPTION
**Pull request by Keller-Zirus**
Might be useful.It will show added custom variables with same type in dialog to select.

### CODE REVIEW

**Comment by JavkhlanK** [comment]
The files you've changed are only used to compile the repo, they won't be added to the final APK.

**Comment by JavkhlanK** [comment]
If you've made changes in smali, please share them in our Discord server instead! We can trust them more then, at least more than binary changes in JARs.

**Comment by Keller-Zirus** [comment]
How do i change this two
mod.agus.jcoderz.editor.manage.block.makeblock.BlockMenu;
com.besome.sketch.editor.LogicEditorActivity;

**Comment by JavkhlanK** [comment]
Just as I've said before, contact us on our Discord server.

**Comment by Keller-Zirus** [comment]
I am new to discord,can you tell where to share in discord

**Comment by JavkhlanK** [comment]
Sure, you can use #general or #contributions-chat for that. The invite to the server is in this repository's README.md file.

**Pull request closed without merging**
