### PR TITLE
Fix: fixed crash in Local Library Manager

### PR DESCRIPTION
**Pull request by Keller-Zirus**
Fixed ConcurrentModificationException error

### CODE REVIEW

**Comment by khaled-0** [comment]
Bruh, they both does the same thing.

**Comment by Keller-Zirus** [comment]
> Bruh, they both does the same thing.

IMG_20210726_182048

**Comment by khaled-0** [comment]
I would suggest using an Iterator so the code would look a bit nice.
But anyways if it works , it works 🐸

**Comment by JavkhlanK** [comment]
I think the entire logic of the activity should be changed, or at least made efficient. For now though, this will be enough.

**Pull request merged**
