### PR TITLE
feat : Project compiling notification.

### PR DESCRIPTION
**Pull request by DevKumar00001**

### CODE REVIEW

**Comment by TechnicalStudioDeveloper** [comment]
XRecorder_10032023_131819
XRecorder_10032023_131947

**Comment by khaled-0** [comment]
Well it's not actually building in the background
the activity/build may get killed by system when you're on background
because the build process is actually not in background thread/service

So this doesn't matter

**Comment by TechnicalStudioDeveloper** [comment]
> Well it's not actually building in the background the activity/build may get killed by system when you're on background because the build process is actually not in background thread/service
> 
> So this doesn't matter

I mean to say that when Sketchware is not open in foreground it is paused for building app so notification will only appear when app is not foreground.

**Comment by TechnicalStudioDeveloper** [comment]
fixed error : [error](https://discord.com/channels/790686719753846785/1042132489084338236/1084527722560233502)

**Comment by TechnicalStudioDeveloper** [comment]
Trying to fix : [Error](https://discord.com/channels/790686719753846785/1042132489084338236/1084856974149169194)

**Comment by DereckySany** [comment]
I liked the addition. but I see no reason to use androidx.core.app.NotificationCompat.Builder
I prefer to use the native libraries as much as possible, so as not to generate incompatibility or the use of one more library, and you can use Notification.Builder natively.

**Comment by TechnicalStudioDeveloper** [comment]
> I liked the addition. but I see no reason to use androidx.core.app.NotificationCompat.Builder I prefer to use the native libraries as much as possible, so as not to generate incompatibility or the use of one more library, and you can use Notification.Builder natively.

IMG_20230412_103023
But it working on Api-23 and I am not sure but it will work on lower devices also.

**Comment by TechnicalStudioDeveloper** [comment]
It only have one bug that I can't fix is If the project is running and app get destroyed from recent screen it will keep showing a notification.

**Review by JavkhlanK — CHANGES_REQUESTED** [review]
I don't think sending notifications about build status while the actual build process itself isn't guaranteed to not get killed (or at least given higher importance than other apps) while it's not in the foreground is worth implementing. It could actually make users believe the app can compile in the background, and then think compiling stopping while multi-tasking being a bug.

**Comment by TechnicalStudioDeveloper** [comment]
> I don't think sending notifications about build status while the actual build process itself isn't guaranteed to not get killed (or at least given higher importance than other apps) while it's not in the foreground is worth implementing. It could actually make users believe the app can compile in the background, and then think compiling stopping while multi-tasking being a bug.

Then it was better earlier that it only shows notification when build is failed or ready to install.

**Comment by TechnicalStudioDeveloper** [comment]
> > I don't think sending notifications about build status while the actual build process itself isn't guaranteed to not get killed (or at least given higher importance than other apps) while it's not in the foreground is worth implementing. It could actually make users believe the app can compile in the background, and then think compiling stopping while multi-tasking being a bug.
> 
> Then it was better earlier that it only shows notification when build is failed or ready to install.

@JavkhlanK

**Comment by TechnicalStudioDeveloper** [comment]
@PranavPurwar If it just show a notification when build is ready then there will no problem.
A install button appear when build ready but if the app is killed then notification will not appear.And same for the failure(If compile issue occured).

**Comment by TechnicalStudioDeveloper** [comment]
> @PranavPurwar If it just show a notification when build is ready then there will no problem. A install button appear when build ready but if the app is killed then notification will not appear.And same for the failure(If compile issue occured).

[This commit](https://github.com/Sketchware-Pro/Sketchware-Pro/pull/803/commits/080efa9facd977cf9a28c083169edb8cb67b87bc) work perfectly as I said @PranavPurwar

**Comment by PranavPurwar** [comment]
and what if some compile issue occurs

**Comment by TechnicalStudioDeveloper** [comment]
> and what if some compile issue occurs

It says app build failed in a notification and a button appear "Show compile log"
and it redirect to error activity.
Till that commit all work as I said

**Comment by TechnicalStudioDeveloper** [comment]
> > and what if some compile issue occurs
> 
> It says app build failed in a notification and a button appear "Show compile log" and it redirect to error activity. Till that commit all work as I said

@PranavPurwar wdyt.
It was not better earlier?

**Pull request closed without merging**
