### PR TITLE
Added the fragment support library

### PR DESCRIPTION
**Pull request by Pranav-sketchware**
Added the latest fragment support library and updated import statement in Jx.java file. (tested on real device)
@JavkhlanK review it when

### CODE REVIEW

**Comment by JavkhlanK** [comment]
I'm not sure if using old support library APIs instead of framework APIs is worth the extra size on projects.

**Comment by Pranav-sketchware** [comment]
Atleast these support libraries are not deprecated till now

**Comment by JavkhlanK** [comment]
they have been lol, it's just that their classes aren't in the artifacts you've used

**Comment by Pranav-sketchware** [comment]
ok lol, I should close this pr

**Pull request closed without merging**
