### PR TITLE
feat : add AAPT2 latest binaries for android.

### PR DESCRIPTION
**Pull request by AlucardTN**
sorry, i uploaded them normally but github rename them with [1] at last.

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Where did you get the binaries from?

**Comment by AlucardTN** [comment]
https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33

**Comment by AlucardTN** [comment]
i told him in issue with named "reminder" to make aapt2 binaries for latest android source and he did

**Comment by JavkhlanK** [comment]
Nice!

**Comment by JavkhlanK** [comment]
I'm just checking the architectures.

**Comment by AlucardTN** [comment]
take you time, dont forget to remove the [1] from their names if possible because i dont know how

**Comment by AlucardTN** [comment]
tbh i didn't found the rename option

**Pull request merged**
