### PR TITLE
fix:Make DebugActivity text actually selectable,Cleanup unnecessary null checks

### PR DESCRIPTION
**Pull request by khaled-0**
findViewById after dialog.show when?
also why null checks?

### CODE REVIEW

**Comment by JavkhlanK** [comment]
turns out that selectable stack trace's still not working, haha

**Comment by khaled-0** [comment]
> turns out that selectable stack trace's still not working, haha

how fast was that, i wal also updating asset/debug.java
anyway

**Comment by JavkhlanK** [comment]
I don't get why you would submit PRs without fully finishing them first

**Comment by khaled-0** [comment]
((TextView) dialog.findViewById(android.R.id.message)).setTextIsSelectable(true);
image

**Comment by khaled-0** [comment]
> I don't get why you would submit PRs without fully finishing them first

i didint think u would merge it instantly, 
please update the other file urself

**Comment by JavkhlanK** [comment]
That file looks poorly formatted, so I'll definitely clean it up & also fix that as well

**Pull request merged**
