### PR TITLE
Use default view editor theme

### PR DESCRIPTION
**Pull request by elfilibusterismo**
This changes will  prevent from using material3 in the view editor

### CODE REVIEW

**Comment by remaker17** [comment]
Hello, good pull request. Can you use
`Theme.MaterialComponents.Light.NoActionBar.Bridge` as parent theme?

Source: Parent theme from main branch.

**Comment by elfilibusterismo** [comment]
> Hello, good pull request. Can you use `Theme.MaterialComponents.Light.Bridge` as parent theme?
> 
> Source: Parent theme from main branch.

I can do that but some widget or specifically FloatingActionButton in editor will still use the box shape.. tho i can use <item name="floatingActionButtonStyle">@style/Widget.MaterialComponents.FloatingActionButton</item> in it to make it circle shape

**Comment by remaker17** [comment]
> > Hello, good pull request. Can you use `Theme.MaterialComponents.Light.Bridge` as parent theme?
> > 
> > Source: Parent theme from main branch.
> 
> I can do that but some widget or specifically FloatingActionButton in editor will still use the box shape.. tho i can use <item name="floatingActionButtonStyle">@style/Widget.MaterialComponents.FloatingActionButton</item> in it to make it circle shape

It it weird that some styles remained from the Material3 theme.

**Comment by elfilibusterismo** [comment]
> > > Hello, good pull request. Can you use `Theme.MaterialComponents.Light.Bridge` as parent theme?
> > > Source: Parent theme from main branch.
> > 
> > 
> > I can do that but some widget or specifically FloatingActionButton in editor will still use the box shape.. tho i can use @style/Widget.MaterialComponents.FloatingActionButton in it to make it circle shape
> 
> It it weird that some styles remained from the Material3 theme.

Yeah, that's why I didn't use .Bridge

**Comment by remaker17** [comment]
@ilyassesalama can you check this pr?

**Comment by ilyassesalama** [comment]
LGTM

**Pull request merged**
