### PR TITLE
feat,fix: Added file extension methods, fixed issue #150

### PR DESCRIPTION
**Pull request by hasrat-ali**

### CODE REVIEW

**Comment by hasrat-ali** [comment]
`@Jbk0#4096` Merge all PR or nub

**Comment by hasrat-ali** [comment]
Me not, you

**Comment by hasrat-ali** [comment]
Mr jbk0

**Comment by hasrat-ali** [comment]
Reply of `who`

**Comment by hasrat-ali** [comment]
You

**Comment by hasrat-ali** [comment]
Jbk0

**Comment by hasrat-ali** [comment]
How ping in #github ?

**Comment by Iyxan23** [comment]
<@345647725422968833>

**Comment by DantaNotEpic** [comment]
<@345647725422968833>

**Comment by Iyxan23** [comment]
ha get pinged

**Comment by hasrat-ali** [comment]
<@574128504451366913>
aha me also por

**Comment by hasrat-ali** [comment]
<@798178395124400159>

**Comment by hasrat-ali** [comment]
<@Hasrat#1250>

**Pull request merged**
