### PR TITLE
Update SketchLogger.java

### PR DESCRIPTION
**Pull request by SENPAi-03**
Replace thread :)

### CODE REVIEW

**Comment by SENPAi-03** [comment]
Improving

**Comment by JavkhlanK** [comment]
And for what reason? Also this won't work with dx / Java 1.7 projects.

**Comment by SENPAi-03** [comment]
Sometimes the app breaks down, also we can replace lambda syntax

**Comment by JavkhlanK** [comment]
Sometimes? When? Breaks down? In what exact way?

**Pull request closed without merging**
