### PR TITLE
del: delete ApkSigner

### PR DESCRIPTION
**Pull request by AlucardTN**
took it like you took ResourceCompiler after adding 20 lines to it

### CODE REVIEW

**Comment by JavkhlanK** [comment]
it's still used in Tools.java tho

**Comment by AlucardTN** [comment]
see what I've said above + I don't fuckin care if it still used in anything

**Comment by JavkhlanK** [comment]
and bruh you know I didn't "steal" Resource Compiler, you haven't made a signle contribution to it

**Comment by AlucardTN** [comment]
does your contribution to it, made it yours class ? then why didn't you make the about activity yours when you changed to the obfuscated recyclerview classes, same as fixing Incremental Compiler ?

**Comment by DantaNotEpic** [comment]
<:hels:835518914821488690>

**Comment by JavkhlanK** [comment]
how practical that I can't send any screenshots of our chat where we agreed on putting my work into your package. dude, it's just a package, you still have plenty of other things that are useful

**Comment by AlucardTN** [comment]
yes, plenty of things that useful but not even working right, then how tf that i have features then ?!

**Comment by ilyassesalama** [comment]
ugh, not again. go jbk0 it's your turn to delete the repo. smh my smh

**Comment by JavkhlanK** [comment]
> yes, plenty of things that useful but not even working right, then how tf that i have features then ?!

work on them maybe?

**Pull request closed without merging**
