### PR TITLE
Update dialog.xml

### PR DESCRIPTION
**Pull request by hsigamerppsspp**
Screenshot_۲۰۲۱۰۸۲۰-۰۰۳۵۲۰
Color+cardx Fix Mod (Ninja Coder)

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Alright we actually don't intend to change most UI parts from vanilla Sketchware in Sketchware Pro, so this wouldn't fit really. I'll make sure to note that in README.md though, that needs to be added.
Another thing, as noted in the README of the repo, please explain why you've changed something, and also, use the correct commit message format next time.

**Comment by NotteShock** [comment]
cansel 😂😂😂🤣😂

**Comment by hsigamerppsspp** [comment]
Shut up, mother of a prostitute

در تاریخ یکشنبه ۲۲ اوت ۲۰۲۱،‏ ۱۰:۴۳ NotteShock ***@***.***>
نوشت:

**Comment by JavkhlanK** [comment]
kinda rude, ain't it

**Pull request closed without merging**
