### PR TITLE
MaterialAlertDialog animation in aB dialog

### PR DESCRIPTION
**Pull request by aquilesTrindade**

### CODE REVIEW

**Comment by remaker17** [comment]
I'm sure alert dialog already has M3 animation.

**Comment by aquilesTrindade** [comment]
> Tenho certeza de que a caixa de diálogo de alerta já possui animação M3.

no, there isn't

**Comment by ilyassesalama** [comment]
Matarial3 already has dialog fade in/out animation by default. Thanks for the contribution though.

**Comment by remaker17** [comment]
> Matarial3 already has dialog fade in/out animation by default. Thanks for the contribution though.

I don't think so, because we are using custom dialog (android.app.Dialog).

**Comment by ilyassesalama** [comment]
I tested with and without his change before closing this PR. There was no difference.

**Comment by aquilesTrindade** [comment]
😂 unbelievable

**Pull request closed without merging**
