### PR TITLE
misc: Changed the splash screen slightly

### PR DESCRIPTION
**Pull request by khaled-0**
gradient color now uses the one from logo
increased logo size instead of getting from mipmap
removed hardcoded delay.

and ZipSigner because that warning was very much bothering

### CODE REVIEW

**Comment by khaled-0** [comment]
Certified by image btw

**Comment by JavkhlanK** [comment]
I've never seen `sp` used for dimensions other than text size before lol

**Comment by khaled-0** [comment]
> I've never seen `sp` used for dimensions other than text size before lol

dp has no difference at all but changed anyway

**Comment by JavkhlanK** [comment]
Now it looks weirdly off in my opinion. I think we should remove the useless activity entirely, and instead, use a splash screen with resource themes.

**Comment by JavkhlanK** [comment]
Nevermind, was due to Android 12 not liking outdated libraries.

**Comment by hasrat-ali** [comment]
> Now it looks weirdly off in my opinion. I think we should remove the useless activity entirely, and instead, use a splash screen with resource themes.

After this [commit](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/803de939f7f6e24c5aa2b884502912ecf27ccf34) now there is no need for it (#397).

**Pull request closed without merging**
