### PR TITLE
Update ConfigActivity.java

### PR DESCRIPTION
**Pull request by hosni-fraj**
feat: added a `custom package `option

### CODE REVIEW

**Comment by hasrat-ali** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/blob/ac1ca5855fbd7dd94a0d2e8931f34d695b982aaf/app/src/main/java/mod/hilal/saif/activities/tools/ConfigActivity.java#L63

Was the new method really necessary while there is already a reliable method? Just asking

https://github.com/Sketchware-Pro/Sketchware-Pro/blob/ac1ca5855fbd7dd94a0d2e8931f34d695b982aaf/app/src/main/java/mod/hilal/saif/activities/tools/ConfigActivity.java#L127

**Comment by hosni-fraj** [comment]
Yes yes , can you remove it?

**Comment by hasrat-ali** [comment]
> Yes yes , can you remove it?

Actually I don't have `write access to this repository` so i can't.

**Comment by hosni-fraj** [comment]
Ok

**Comment by hasrat-ali** [comment]
> Ok

But I can remove after merged.

**Comment by Iyxan23** [comment]
> Yes yes , can you remove it?

@hosni-fraj The code is from your fork's branch, you could edit it yourself by clicking this link: https://github.com/hosni-fraj/Sketchware-Pro/edit/patch-6/app/src/main/java/mod/hilal/saif/activities/tools/ConfigActivity.java

**Comment by hasrat-ali** [comment]
Wy?

**Comment by hosni-fraj** [comment]
We already discussed about this in Discord server.
It may break the (already) created project, according to jbk0

**Comment by hosni-fraj** [comment]
And pls check idea channel

**Comment by hasrat-ali** [comment]
> We already discussed about this in Discord server.
> It may break the (already) created project, according to jbk0

Not, I don't think it will break (damage) already created projects. If implemented properly.

**Comment by JavkhlanK** [comment]
Well it wouldn't break projects immediately, but probably would when users change settings for a project. Then, a notice about the new feature should be required (would look nub tho)

**Comment by hosni-fraj** [comment]
So, i will reopen the pull request

**Comment by ilyassesalama** [comment]
This pull request will be closed after 5 days if there are no updates.

**Pull request closed without merging**
