### PR TITLE
feat: check description for changes😶

### PR DESCRIPTION
**Pull request by PranavPurwar**
- remove references of Tablayout in MainActivity.java and removed Tablayout from core XML file
- added logger to custom path(useful for debugging crashes for users not having rooted phones)
- Added external logger on DebugActivity.java

### CODE REVIEW

**Comment by JavkhlanK** [comment]
didn't we discuss adding the older fragment support library already?

**Comment by JavkhlanK** [comment]
and also, the your decompiled Kx class is broken.

**Comment by Pranav-sketchware** [comment]
that's why I put it in work in progress doe

**Comment by Pranav-sketchware** [comment]
Kx.java
Screenshot_2021-07-27-17-38-23
doe that's what I got in decompiler

**Comment by JavkhlanK** [comment]
decompiled code doesn't always work without modifying it

**Comment by Pranav-sketchware** [comment]
ok doe I will Undo it soonTM

**Comment by JavkhlanK** [comment]
what's with the new file now?

**Comment by Pranav-sketchware** [comment]
replaced all those files described above with original ones

**Pull request closed without merging**
