### PR TITLE
Pin Gradle actions to specific versions

### PR DESCRIPTION
**Pull request by ArjunaKumarMohanta**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
what's the point in pinning a specific version? doesn't that just force more frequent updates since automatic ones from e.g. 2.4.2 to 2.4.3 are disabled?

**Comment by PranavPurwar** [comment]
why do they enquire you about sketchware pro buildscript

**Comment by JavkhlanK** [comment]
> I consistently receive inquiries from individuals stating that the build script is susceptible to x/y/z vulnerabilities, even though the 'v2' tag has been redirected to a non-vulnerable version of these dependencies. This is why I make these changes.

just tell them that it's automatically been "redirected" to a non-vulnerable version then?

**Comment by PranavPurwar** [comment]
we dont use configuration cache

**Comment by JavkhlanK** [comment]
Just ignore that, the repo's already using v2:  
image

**Pull request closed without merging**
