### PR TITLE
Some UI Improvements 

### PR DESCRIPTION
**Pull request by trindadedev13**
Screenshot_20241227-225427
Screenshot_20241227-225434
Screenshot_20241227-225446

I preferred to open a PR, in case you don't like it, or want some changes.

### CODE REVIEW

**Comment by aikrq** [comment]
`push -f` `push -f` `push -f` `push -f` `push -f` `push -f` `push -f` `push -f`

**Review by aikrq — CHANGES_REQUESTED** [review]
Can you move it to `UI#getShapedBackgroundForList(Int, List)`?

Example usage:
```
@DrawableRes int bg = UI.getShapedBackgroundForList(position, list);
view.setBackgroundResource(bg);
```

**Comment by trindadedev13** [comment]
> Can you move it to `UI#getShapedBackgroundForList(Int, List)`?
> 
> Example usage:
> 
> ```
> @DrawableRes int bg = UI.getShapedBackgroundForList(position, list);
> view.setBackgroundResource(bg);
> ```

no, i can kill you,
well, joke, later i can do this

**Comment by trindadedev13** [comment]
@aikrq  done, you can merge

**Pull request merged**
