### PR TITLE
Update SketchApplication.java

### PR DESCRIPTION
**Pull request by hsigamerppsspp**
DONT EDIT IN AD MOB

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Why not edit? What does this commit do?

**Comment by khaled-0** [comment]
You are removing imports.
Resolve class name how

**Comment by JavkhlanK** [comment]
This PR will be closed in a day if there won't be any response.

**Comment by khaled-0** [comment]
Just close it already

**Comment by JavkhlanK** [comment]
Not responding for a week and also useless changes (without explanation)

**Pull request closed without merging**
