### PR TITLE
Fixed Zipalign error and update aapt2 binary 

### PR DESCRIPTION
**Pull request by freindlytech**
Here is the error screenshot

Screenshot_20220515-060318

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Can I ask wherr you got the binaries from? From which branch on AOSP were they compiled from? Were any changes made to AOSP to get working binaries, and if so, which?

**Comment by freindlytech** [comment]
I am not here for explaining cauz it's really frustrating  , I just want to help if you want you can use this fix cauz it's a serious issues that preventing app from building completely btw I get the source from official site

**Comment by JavkhlanK** [comment]
What site?

**Comment by freindlytech** [comment]
https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2/

**Comment by JavkhlanK** [comment]
That's the official code repository. I was talking about the already compiled binaries you shared here.

**Comment by freindlytech** [comment]
I compiled it on my own by taking references and learning things

**Comment by JavkhlanK** [comment]
Could you instead please share what you had to do to compile those binaries? That way we can trust the binaries since they're built by us.

**Comment by JavkhlanK** [comment]
For example, tell what you had to change in build scripts to build for aarch64 Android.

**Comment by freindlytech** [comment]
I take reference from termux developer you can visit official termux repo to get the answer you want

**Comment by JavkhlanK** [comment]
Alright, thanks a lot!

**Pull request merged**
