### PR TITLE
del: remove R8Executor

### PR DESCRIPTION
**Pull request by AlucardTN**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Dp.java does have a reference to it, so it's not useless right now. It's just not finished.

**Comment by AlucardTN** [comment]
it's not implemented there, means i can remove it you are using if (false) means the method will not even executed son, remove that

**Comment by JavkhlanK** [comment]
why remove it tho?

**Comment by AlucardTN** [comment]
because

**Comment by DantaNotEpic** [comment]
big por modir moment

**Comment by AlucardTN** [comment]
shut

**Comment by DantaNotEpic** [comment]
rud <a:fastsad:816072729148260353>

**Pull request closed without merging**
