### PR TITLE
remove unnecessary allegations against android studio

### PR DESCRIPTION
**Pull request by PranavPurwar**
you guys wrote that there is issue with android studio/build tools while it's just because they didn't made it for doing illegal things like modding

### CODE REVIEW

**Comment by khaled-0** [comment]
ha

**Comment by Iyxan23** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by PranavPurwar** [comment]
what the f

**Comment by JavkhlanK** [comment]
You replaced `an issue` with `problem`, that's it? Sorry, but that's neither helpful, nor proper feedback, especially with that PR description.

**Comment by PranavPurwar** [comment]
> You replaced `an issue` with `problem`, that's it? Sorry, but that's neither helpful, nor proper feedback, especially with that PR description.

explain then what else could be done

**Comment by JavkhlanK** [comment]
Nothing, the readme is fine already. Useless nitpicking isn't needed.

**Pull request closed without merging**
