### PR TITLE
Github Manager - to Push SourceCode

### PR DESCRIPTION
**Pull request by AndroXStudiO**

### CODE REVIEW

**Comment by TechnicalStudioDeveloper** [comment]
Bro,It commits in Git but no files are added.Am I making mistake?

**Comment by AndroXStudiO** [comment]
> Bro,It commits in Git but no files are added.Am I making mistake?

Your API key is valid?

**Comment by AndroXStudiO** [comment]
> Bro,It commits in Git but no files are added.Am I making mistake?

Or You can commit files as default.

**Comment by bondhusoftware** [comment]
> > > Bro,It commits in Git but no files are added.Am I making mistake?
> > 
> > 
> > Your API key is valid?
> 
> Yeah,It is valid as I only have one which I use to commit.

Screenshot_2023-03-28-12-41-38-84_423e58f25c30a02453fa5d8c82fc37f2


Okey now Leave this box empty (as default) and try again

**Comment by AndroXStudiO** [comment]
> > > Bro,It commits in Git but no files are added.Am I making mistake?
> > 
> > 
> > Your API key is valid?
> 
> Yeah,It is valid as I only have one which I use to commit.


> > Bro,It commits in Git but no files are added.Am I making mistake?
> 
> 
> Your API key is valid?

Yeah,It is valid as I only have one which I use to commit.


Screenshot_2023-03-28-12-41-38-84_423e58f25c30a02453fa5d8c82fc37f2


Okey now Leave this box empty (as default) and try again

**Comment by RockAriful** [comment]
> rip commits 😷

@TechnicalStudioDeveloper 

> Bro,It commits in Git but no files are added.Am I making mistake?

#Fixed!

**Comment by TechnicalStudioDeveloper** [comment]
> > rip commits 😷
> 
> @TechnicalStudioDeveloper
> 
> > Bro,It commits in Git but no files are added.Am I making mistake?
> 
> #Fixed!

Bro I just want to ask a question that.
Suppose I and my friend is working on a same project published at get hub using your new feature suppose that my friend have made changes to main activity and I edited another activity my friend have pushed a commit while I didn't.So I need to pull the changes that he made.
Then I will lost changes that I made?

**Comment by TechnicalStudioDeveloper** [comment]
> > > rip commits 😷
> > 
> > 
> > @TechnicalStudioDeveloper
> > > Bro,It commits in Git but no files are added.Am I making mistake?
> > 
> > 
> > #Fixed!
> 
> Bro I just want to ask a question that. Suppose I and my friend is working on a same project published at github using your new feature suppose that my friend have made changes to main activity and I edited another activity my friend have pushed a commit while I didn't.So I need to pull the changes that he made. Then I will lost changes that I made?

@AndroXStudiO Please note that it is important question for a users who will work as team.

**Comment by TechnicalStudioDeveloper** [comment]
@AndroXStudiO please reply

**Pull request closed without merging**
