### PR TITLE
feat: Adding ElseIf & Else Blocks

### PR DESCRIPTION
**Pull request by khaled-0**
Here's what it looks like 
You can stack as many else if as necessary
Block structure should be like
```
If
else if 
else if
else
```
With as much else if as needed in middle
preview
IDK how's this still not a thing😐 Specially when this is a core function.

### CODE REVIEW

**Comment by PranavPurwar** [comment]
is this really needed ?

**Comment by PranavPurwar** [comment]
core function does not mean that it's necessary. also custom blocks or asd can be used instead of this

**Comment by ilyassesalama** [comment]
Looks good imo, i always needed something like this in sketchware.

**Comment by hassanmahfuj** [comment]
If you want to make a small app, then the block system is good, but if you work on a big project, the block system s*cks (Lags, Finding, Managing). According to this, "else if" block may also exist.

**Comment by hassanmahfuj** [comment]
Fun Fact : After this conversation I found out that many new blocks have been added by turning on the "Built-in blocks" in the "Mod settings".  I haven't used one yet.

**Pull request closed without merging**
