### PR TITLE
Minimum SDK 24

### PR DESCRIPTION
**Pull request by subhash16**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
any benefit? i don't see any

**Comment by subhash16** [comment]
> any benefit? i don't see any

Target SDK 34 so minimum SDK should 24 coz 21 is too low

**Comment by JavkhlanK** [comment]
that's not a benefit. the target SDK is not related to the minimum, you can change both, regardless of the other. you need an actual benefit, like "library x only supports minSdk 24 and it's used in 70 % of projects" (but that doesn't exist)

**Comment by subhash16** [comment]
> that's not a benefit. the target SDK is not related to the minimum, you can change both, regardless of the other. you need an actual benefit, like "library x only supports minSdk 24 and it's used in 70 % of projects" (but that doesn't exist)

Ok

**Pull request closed without merging**
