### PR TITLE
feat: Added a new Library Downloader Dialog

### PR DESCRIPTION
**Pull request by BlueCatSoftware**

### CODE REVIEW

**Comment by hasrat-ali** [comment]
such a messy pull request.
Please follow commit guidelines.

Must read code formatting and commit guidelines.

**Comment by hasrat-ali** [comment]
23 commits just for one class.

**Comment by BlueCatSoftware** [comment]
> such a messy pull request.
> Please follow commit guidelines.
> 
> Must read code formatting and commit guidelines.

Bruh which path is messy.
Why do you like saying people's codes are messy. 
It might be messy but the word MESSY sounds unwanted or useless.
Anyway I will fix it just

**Comment by JavkhlanK** [comment]
well, what's new/been changed/improved?

**Comment by khaled-0** [comment]
Where description 😐
Codes aren't self explanatory yk

**Comment by hasrat-ali** [comment]
> > such a messy pull request.
> > Please follow commit guidelines.
> > Must read code formatting and commit guidelines.
> 
> Bruh which path is messy.
> Why do you like saying people's codes are messy.
> It might be messy but the word MESSY sounds unwanted or useless.
> Anyway I will fix it just

Bruh, see for yourself.
You only made changes to one class and have 23 commits.

Commits doesn't matter if you format your code better.
If the codes are well formatted then it will be easier for us to understand what you have done.

**Comment by BlueCatSoftware** [comment]
> > > such a messy pull request.
> > > Please follow commit guidelines.
> > > Must read code formatting and commit guidelines.
> > 
> > 
> > Bruh which path is messy.
> > Why do you like saying people's codes are messy.
> > It might be messy but the word MESSY sounds unwanted or useless.
> > Anyway I will fix it just
> 
> Bruh, see for yourself.
> You only made changes to one class and have 23 commits.
> 
> Commits doesn't matter if you format your code better.
> If the codes are well formatted then it will be easier for us to understand what you have done.

Ok. I added new dialog

**Comment by BlueCatSoftware** [comment]
> Where description 😐
> Codes aren't self explanatory yk

**Comment by JavkhlanK** [comment]
It's not completely new though, apparently you added to some EditTexts TextInputLayouts as parents. A PR description of what exactly you have changed would be very useful, especially with that many commits.

**Comment by BlueCatSoftware** [comment]
> It's not completely new though, apparently you added to some EditTexts TextInputLayouts as parents. A PR description of what exactly you have changed would be very useful, especially with that many commits.

Okk Iwill update the descriptions..
Bythe way have you tested it

**Comment by JavkhlanK** [comment]
You should actually test it out too, not just us.

**Comment by khaled-0** [comment]
You also have to reset the error in textinputlayout.
Use ```setError(null)```

**Comment by BlueCatSoftware** [comment]
> You also have to reset the error in textinputlayout.
> Use `setError(null)`

No need for that anymore. Cos I don't think the PR is actually needed anymore

**Pull request closed without merging**
