### PR TITLE
feat: add latest AAPT for Android-11

### PR DESCRIPTION
**Pull request by AlucardTN**
i added AAPT from the latest source of android-11
i got them from : https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt
yes i have tested the binaries out.
also please remove the [1] from the aapt2 binaries if possible.

### CODE REVIEW

**Comment by JavkhlanK** [comment]
How's the performance compared to the stock AAPT compiled by Sketchware's team?

**Comment by AlucardTN** [comment]
kinda faset bor 🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by AlucardTN** [comment]
accept or dumb

**Comment by JavkhlanK** [comment]
you

**Pull request merged**
