### PR TITLE
Update library_downloader_dialog.xml

### PR DESCRIPTION
**Pull request by BlueCatSoftware**
Changed edittext to textinputlayout

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Should work fine, but that needs some changes in the Java file using it. Could you modify it too?

**Comment by BlueCatSoftware** [comment]
> Should work fine, but that needs some changes in the Java file using it. Could you modify it too?

Yes, no Problem

**Comment by BlueCatSoftware** [comment]
> Should work fine, but that needs some changes in the Java file using it. Could you modify it too?
What's the java file path? 
It should be in hey studio path

**Comment by JavkhlanK** [comment]
It's used in `mod.hey.studios.project.library.LibraryDownloader`.

**Pull request closed without merging**
