### PR TITLE
new Theme google 

### PR DESCRIPTION
**Pull request by moderGamer**
Screenshot_20230217-121847_Sketchware Pro

Activate the Material 3 theme and give the user a stylish look, just check the style, ignore the other manipulations, thanks

#Moder_Gamer

### CODE REVIEW

**Comment by hasrat-ali** [comment]
As you already working on it, i just convert to draft

**Comment by moderGamer** [comment]
> 

Excellent!  I'm done, check it because there are some problems, such as the size of the texts and...

**Comment by khaled-0** [comment]
Why is this pr a dumpster fire?
Why change match_parent to fill_parent
Why modify useless/irrelevant files?

**Comment by hasrat-ali** [comment]
In simple word 'Sketchware Pro isn't ready for Material 3/You' for now.

**Comment by hasrat-ali** [comment]
So it's worthless. And since they're unworthy/unnecessary changes this pr not gonna merge.

**Comment by moderGamer** [comment]
@hasrat-ali + @khaled-0  

Hi, I just changed the style of tabLayout and TextInputLayout. If you feel that my changes don't help, then activate the Material 3 theme yourself because you have implemented the latest version in your build, and according to many people, it is better to update the style of the program.

**Comment by hasrat-ali** [comment]
Yeah, we will do that.

**Comment by moderGamer** [comment]
> Yeah, we will do that.

Thank you and I will try my best, maybe I have satisfied you and please remove the dead activities

**Pull request closed without merging**
