### PR TITLE
Update Lx.java

### PR DESCRIPTION
**Pull request by moderGamer**
feat: add last Version Gson and Androidx(AppCompat)

### CODE REVIEW

**Comment by moderGamer** [comment]
> 

what?

**Comment by PranavPurwar** [comment]
Sketchware doesn't use gradle, this is useless

**Comment by moderGamer** [comment]
> 

I know that I did Android Studio to output the project, who knows, maybe Gradle will be supported in the future

**Comment by TechnicalStudioDeveloper** [comment]
> > 
> 
> I know that I did Android Studio to output the project, who knows, maybe Gradle will be supported in the future

I know because my project gives error because of wrong gradle version in Android Studio that why I updated it.

**Comment by TechnicalStudioDeveloper** [comment]
bro! The version you updated is more higher than the Sketchware compile in run build.I think that is why hasrat-ali marked this as invalid.

**Comment by moderGamer** [comment]
> 

Maybe, but Hasrat should update the Androidx library, can't individual users use a custom library?!
@hasrat-ali  @TechnicalStudioDeveloper

**Comment by hasrat-ali** [comment]
Pls don't mention anyone.
Will see when we update it.

**Comment by TechnicalStudioDeveloper** [comment]
> > 
> 
> Maybe, but Hasrat should update the Androidx library, can't individual users use a custom library?! @hasrat-ali @TechnicalStudioDeveloper

Changing a single line of code to change lib version is not enough in my opinion because updating a lib can break old projects and to prevent them from throwing error Sketchware pro should make it compatible with new that version which is hard in my opinion.

**Comment by TechnicalStudioDeveloper** [comment]
> > 
> 
> Maybe, but Hasrat should update the Androidx library, can't individual users use a custom library?! hasrat-ali @TechnicalStudioDeveloper

yeah! from user view it is necessary that is why there is **Exclude built in lib**...

**Comment by moderGamer** [comment]
> 

Great, so there is nothing left to say, I can also update the libraries, but I'm afraid it will be rejected again

**Comment by TechnicalStudioDeveloper** [comment]
> > 
> 
> Great, so there is nothing left to say, I can also update the libraries, but I'm afraid it will be rejected again

😂😹 That's why I am also afraid and made a much small contribution.

**Comment by moderGamer** [comment]
> 
Yes, it is better for Hasrat Ali or jbk0 to update it because many of the old methods of Android X are obsolete, for example, locking ViewPager, which was removed or changed in version 1.6.1.

**Comment by JavkhlanK** [comment]
> > 
> 
> Great, so there is nothing left to say, I can also update the libraries, but I'm afraid it will be rejected again

That's true because I can't trust everyone to do such a complicated task properly.

**Comment by moderGamer** [comment]
> 

Yes, you are absolutely right, there is no doubt about it, so I leave the update of important and main libraries to you, just try to add it to the latest available version.

and add new Block 

```java
recyclerview1.getAdapter().notifyDataSetChanged();
```

I think you forgot this code, make it public to refresh the data

**Comment by moderGamer** [comment]
> 

Done.

**Pull request closed without merging**
