### PR TITLE
Added font previewing for non Latin languages

### PR DESCRIPTION
**Pull request by skinvent**
If you got Non latin font like Chinese arabic Japanese russian you can preview it now

### CODE REVIEW

**Comment by JavkhlanK** [comment]
For the future, please read the README about how to contribute.

**Comment by skinvent** [comment]
Sorry I forgot the branch  creating I have read the md file

**Comment by JavkhlanK** [comment]
(I'm talking about commit messages)

**Comment by ilyassesalama** [comment]
This change has been merged with [commit](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/8867ab78687e069dd0c107c5e16a854c8482f86d#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103). Though, I think it should be reverted, or at least use a better approach.

**Comment by skinvent** [comment]
and why can you please explain ?

**Comment by trindadedev13** [comment]
@skinvent your PR was closed because in PR https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1256 you pushed the same commits + the one from LoadingIndicator.

**Comment by skinvent** [comment]
ouh Sorry my terminal is broken those days I must change it

**Pull request closed without merging**
