### PR TITLE
feat: adaptive icon

### PR DESCRIPTION
**Pull request by trindadedev13**

### CODE REVIEW

**Comment by RoyTheReal** [comment]
Adaptive icon doesn't work. You can't upload foreground, background or monochrome images

**Comment by ilyassesalama** [comment]
How is this different than the one we already have?

**Comment by trindadedev13** [comment]
> Adaptive icon doesn't work. You can't upload foreground, background or monochrome images

wdym

**Comment by trindadedev13** [comment]
> How is this different than the one we already have?

I told you on telegram, the current adaptive icon doesn't work on Android 12

**Comment by hasrat-ali** [comment]
This looking shit.

Screenshot_2024-12-02-14-09-07-330_com miui home-edit

**Comment by trindadedev13** [comment]
> This looking shit.
> 
> Screenshot_2024-12-02-14-09-07-330_com miui home-edit

not so much

**Comment by hasrat-ali** [comment]
<del>not</del> so much

**Pull request closed without merging**
