### PR TITLE
Brand new external library manager

### PR DESCRIPTION
**Pull request by khaled-0**
Implementing [New Local Library Manager](https://discord.com/channels/790686719753846785/1048439277832380476)

**NOTE:** This breaks compatibility with old `Local library manager`. You'll have to re-download all of your libraries and re enable them from ```Library > External Library Manager```

image

### CODE REVIEW

**Comment by TechnicalStudioDevelopers** [comment]
@khaled-0 bro Library name not visible.

**Comment by TechnicalStudioDevelopers** [comment]
@khaled-0 bro lib names are not visible and there is no option to turn it off and on.
Screenshot_2023-02-06-19-45-34-955_com sketchware remod

**Comment by ilyassesalama** [comment]
That FAB looks very nice. Also, can you add some margin between the toolbar and libraries' names.
image

**Comment by khaled-0** [comment]
Ayo it's done
@TechnicalStudioDevelopers try now

**Comment by TechnicalStudioDevelopers** [comment]
> Ayo it's done @TechnicalStudioDevelopers try now

@khaled-0 is there is no option for dx and d8 it just only compiling dx and d8 is compiling as dx and that why I am getting error in my project when I compiling it using this new library manager.
But when I tried old lib manager my project work perfectly.
Please fix it.
But New library manager is very good than the old one.

**Comment by khaled-0** [comment]
> > Ayo it's done @TechnicalStudioDevelopers try now
> 
> @khaled-0 is there is no option for dx and d8 it just only compiling dx and d8 is compiling as dx and that why I am getting error in my project when I compiling it using this new library manager. But when I tried old lib manager my project work perfectly. Please fix it. But New library manager is very good than the old one.

Added a checkbox to use Dx explicitly

**Comment by moderGamer** [comment]
@khaled-0 -> You can use the check box or at least the material switch or the photo button to select or delete the library, this does not look good

**Comment by moderGamer** [comment]
/storage/emulated/0/.sketchware/libs/local_libs/
not Found
to new version
Screenshot_20230315-020036_Sketchware Pro


So where is the local library?  Do you code and test?  Well, a child can also code, first test your code on the program and then release it
@khaled-0

**Comment by moderGamer** [comment]
```shell
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:355)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:307)
	at mod.khaled.librarymanager.ExternalLibraryDownloaderDialog$1.lambda$onDownloadComplete$0$mod-khaled-librarymanager-ExternalLibraryDownloaderDialog$1(ExternalLibraryDownloaderDialog.java:148)
	at mod.khaled.librarymanager.ExternalLibraryDownloaderDialog$1$$ExternalSyntheticLambda0.onSaveComplete(Unknown Source:6)
	at mod.khaled.librarymanager.ExternalLibraryDownloader.lambda$saveLibraryToDisk$0$mod-khaled-librarymanager-ExternalLibraryDownloader(ExternalLibraryDownloader.java:62)
	at mod.khaled.librarymanager.ExternalLibraryDownloader$$ExternalSyntheticLambda1.onComplete(Unknown Source:8)
	at mod.hey.studios.project.library.LibraryDownloader$BackTask.onPostExecute(LibraryDownloader.java:640)
	at mod.hey.studios.project.library.LibraryDownloader$BackTask.onPostExecute(LibraryDownloader.java:589)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by TechnicalStudioDeveloper** [comment]
> /storage/emulated/0/.sketchware/libs/local_libs/ not Found to new version Screenshot_20230315-020036_Sketchware Pro
> 
> So where is the local library? Do you code and test? Well, a child can also code, first test your code on the program and then release it @khaled-0

look like my GitHub project

**Comment by PranavPurwar** [comment]
> /storage/emulated/0/.sketchware/libs/local_libs/ not Found to new version Screenshot_20230315-020036_Sketchware Pro
> 
> So where is the local library? Do you code and test? Well, a child can also code, first test your code on the program and then release it @khaled-0

Learn to "code" yourself and make a better version then, if you yourself don't know how to do stuff, you mustn't argue with others. You aren't even using the correct build anyways.

**Comment by khaled-0** [comment]
sick 🔥🔥🔥

**Comment by TechnicalStudioDeveloper** [comment]
> > /storage/emulated/0/.sketchware/libs/local_libs/ not Found to new version Screenshot_20230315-020036_Sketchware Pro
> > So where is the local library? Do you code and test? Well, a child can also code, first test your code on the program and then release it @khaled-0
> 
> Learn to "code" yourself and make a better version then, if you yourself don't know how to do stuff, you mustn't argue with others. You aren't even using the correct build anyways.

Is this playground for fighting 😅

**Comment by TechnicalStudioDeveloper** [comment]
@khaled-0 there are some lib that is not added by local lib manager can this lib manager can do this?
If it can,this it may be the best.

**Comment by khaled-0** [comment]
> @khaled-0 there are some lib that is not added by local lib manager can this lib manager can do this? If it can,this it may be the best.

probably not since it's still using the same library downloader.
 but if it's not downloading because it's in an external repo then you can try adding the repo as a source.
 
btw, what are some libraries that it can't download properly? Giving some list would help

**Comment by TechnicalStudioDeveloper** [comment]
> > @khaled-0 there are some lib that is not added by local lib manager can this lib manager can do this? If it can,this it may be the best.
> 
> probably not since it's still using the same library downloader. but if it's not downloading because it's in an external repo then you can try adding the repo as a source.
> 
> btw, what are some libraries that it can't download properly? Giving some list would help

org.jruby.joni:joni:2.1.48
[link](https://mvnrepository.com/artifact/org.jruby.joni/joni/2.1.48)

Or if this lib can be added then please tell me how.

**Comment by khaled-0** [comment]
> 

well there's no .aar available for this library
So it's currently not possible but maybe in future we'll add support for jar files too

**Comment by TechnicalStudioDeveloper** [comment]
> > 
> 
> well there's no .aar available for this library So it's currently not possible but maybe in future we'll add support for jar files too

ok but can I add it manually ??

**Comment by khaled-0** [comment]
> > > 
> > 
> > 
> > well there's no .aar available for this library So it's currently not possible but maybe in future we'll add support for jar files too
> 
> ok but can I add it manually ??

yes, check reply on discord

**Comment by TechnicalStudioDeveloper** [comment]
> 

@khaled-0 I mean to say that It looks like my [GitHub repository](https://github.com/TS-Code-Editor/TS-Code-Editor)

**Comment by PranavPurwar** [comment]
> > > /storage/emulated/0/.sketchware/libs/local_libs/ not Found to new version Screenshot_20230315-020036_Sketchware Pro
> > > So where is the local library? Do you code and test? Well, a child can also code, first test your code on the program and then release it @khaled-0
> > 
> > 
> > Learn to "code" yourself and make a better version then, if you yourself don't know how to do stuff, you mustn't argue with others. You aren't even using the correct build anyways.
> 
> Is this playground for fighting 😅

Its not a place for alleging others either

**Comment by moderGamer** [comment]
> > 
> 
> well there's no .aar available for this library So it's currently not possible but maybe in future we'll add support for jar files too

Don't add anything, it's no use at all, the way you want to do it, we have to edit hundreds of libraries, the same local library, it's better to block this request and don't think about it anymore.

**Comment by moderGamer** [comment]
> 

Everyone talks, don't talk, you're not even of legal age, let's make it count, your words have no value, you're just a 15-year-old kid, go, you're 18, come on.

**Comment by PranavPurwar** [comment]
> > > 
> > 
> > 
> > well there's no .aar available for this library So it's currently not possible but maybe in future we'll add support for jar files too
> 
> Don't add anything, it's no use at all, the way you want to do it, we have to edit hundreds of libraries, the same local library, it's better to block this request and don't think about it anymore.

Respectfully, your opinion is trash

**Comment by moderGamer** [comment]
> 

Well actually I don't care about you goodbye

**Comment by khaled-0** [comment]
that did not last very long lmao

**Comment by hasrat-ali** [comment]
Well, it's been a year, no activity and looks like there won't be any. So I'm closing it.

**Pull request closed without merging**
