### PR TITLE
Binding support, and clean up unused resources

### PR DESCRIPTION
**Pull request by ilyassesalama**
I ensured everything works fine before opening this PR, but I still need others' reviews.

### CODE REVIEW

**Review by JavkhlanK — APPROVED** [review]
i checked for usages of all removed files by filename (occurrences of `layout.<filename>`, `@layout/<filename>`, and even just `<filename>` after manual filtering) and by resource ID in public-stable-ids.txt/public.xml and found no uses of them. Let's hope there's no massive usage of `Resources#getIdentifier(String, String, String)`

also did a quick runtime test without crashes

**Comment by CyberXCoder-6649** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processMinApi21DebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     public-stable-ids.txt: error: failed reading stable ID file.


* Try:

When building Sketchware-Pro (assembleDebug)

**Comment by JavkhlanK** [comment]
did you try building on a Windows host? that's untested by us, try using WSL and in a Linux filesystem if you are

**Comment by CyberXCoder-6649** [comment]
> did you try building on a Windows host? that's untested by us, try using WSL and in a Linux filesystem if you are

Oh i tried Using AndroidIDE i will try with any other way

**Pull request merged**
