### PR TITLE
External Links

### PR DESCRIPTION
**Pull request by TechnicalStudioDeveloper**
Please note that Sketchware will load file from : https://github.com/TechnicalStudioDeveloper/Sketchware-pro-data.github.io
@NiceSapien If you wanna merge it with website repository please inform me I will merge that file in Sketchware pro website repo.

### CODE REVIEW

**Comment by hasrat-ali** [comment]
What is this lamo

**Comment by Kevincoderpro** [comment]
yes what is it

**Comment by TechnicalStudioDeveloper** [comment]
To : @JavkhlanK @hasrat-ali @Kevincoderpro @NiceSapien 
[Video](https://dl.dropbox.com/s/6h40qjvyi3mrofs/XRecorder_19022023_192829.mp4?dl=0)

Modify External links on : [Repo](https://github.com/TechnicalStudioDeveloper/Sketchware-pro-data.github.io) or Merge it with @NiceSapien repository.

**Comment by TechnicalStudioDeveloper** [comment]
> To : @JavkhlanK @hasrat-ali @Kevincoderpro @NiceSapien [Video](https://dl.dropbox.com/s/6h40qjvyi3mrofs/XRecorder_19022023_192829.mp4?dl=0)
> 
> Modify External links on : [Repo](https://github.com/TechnicalStudioDeveloper/Sketchware-pro-data.github.io) or Merge it with @NiceSapien website.

**Comment by TechnicalStudioDeveloper** [comment]
# External Links
There is a file [`main.json`](https://github.com/TechnicalStudioDeveloper/Sketchware-pro-data.github.io/blob/Main/main.json) . Sketchware Pro load this file from the repository and shows the data.
The parent of the data must be an array. Inside that array there are objects.
The object inside the array carries some properties as follows.

| Property | Data | Use |
| --- | --- | --- |
| title | String | Show the name/title of the item in Sketchware pro. |
| TextviewSize | Int[from `10` to `50`] | Set the title size |
| clickable | String [`"true"`/`"false"`] | Set `"true"` if url is present to redirect the user and vice-versa. |
| url | String[`"Url"`] | Set the url to redirect the user to an available browser and set the `"clickable"` property to `"true"` OR to load the favicon of the website if `ShouldShowFavicon` is `true`. |
| hasChild | String [`"true"`/`"false"`] | Set `"true"` if the object has child and `"false"` if the object has no child. |
| Child | Array[Object] | Represents that the current object has some child and the object is a parent. |
| titleColor | color | Sets the color of title |
| ShouldShowFavicon | Boolean | Set `true` if you want to thumbnail of the website or `false` if you do not want. |

**Pull request closed without merging**
