### PR TITLE
Update proguard to support java 11

### PR DESCRIPTION
**Pull request by PranavPurwar**
The currently used version doesn't support Java 11 which is now availablw for use

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Why did you add both base and core?

**Comment by NiceSapien** [comment]
Noice

**Comment by PranavPurwar** [comment]
.

**Comment by Arashvscode** [comment]
> .

حتی فکرشم نکن

**Comment by PHANTOM-XOTIC** [comment]
دیوانه

**Pull request merged**
