### PR TITLE
MoreBlock with custom type

### PR DESCRIPTION
**Pull request by Keller-Zirus**
Can create moreblock with custom type

### CODE REVIEW

**Comment by JavkhlanK** [comment]
nice massive commits but what exactly happened to res/values/ids.xml? it's been modified a lot, but why? and also, your commit messages sadly don't follow the guidelines, please read them.

**Comment by Keller-Zirus** [comment]
You mean,I don't need to modify res/values/ids.xml and rewrite commit massages.

**Comment by Keller-Zirus** [comment]
> nice massive commits but what exactly happened to res/values/ids.xml? it's been modified a lot, but why? and also, your commit messages sadly don't follow the guidelines, please read them.

You mean,I don't need to modify res/values/ids.xml and rewrite commit massage.

**Comment by JavkhlanK** [comment]
of course you can change ids.xml, but I was asking why there were 3k changes. if possible, please try to not add resource IDs as they're painful to manage and are probably way more effort than to not give views IDs. instead, you can create views at runtime and set their LayoutParams.
and also yeah, the commit messages should be re-written to follow the guidelines.

**Pull request closed without merging**
