### PR TITLE
Feat : drag and drop to arrange in blocks manager 

### PR DESCRIPTION
**Pull request by Mustiy0**

### CODE REVIEW

**Comment by ilyassesalama** [comment]
Please always include a screenshot or a screen record of what you've added/changed so the team can know what to review exactly.

**Comment by Mustiy0** [comment]
https://github.com/user-attachments/assets/85f156d3-d0da-407a-95f3-f2d9413f40ed

**Comment by Mustiy0** [comment]
@ilyassesalama done

**Comment by laymintu** [comment]
Wow, i really need this, i have 30 + more blocks so i can't scroll and find them

**Pull request merged**
