### PR TITLE
feat: sending crash logs to discord through webhooks

### PR DESCRIPTION
**Pull request by PranavPurwar**
just change webhook_url with actual discord webhook url through github actions or manually for release idk

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Seems good enough after slight testing. Thanks!

**Comment by PranavPurwar** [comment]
DebugActivity can be removed now, btw

**Comment by JavkhlanK** [comment]
1 kB saved 😱😱

For real though, good suggestion, thanks.

**Comment by PranavPurwar** [comment]
its actually 1.7K

**Pull request merged**
