### PR TITLE
feat: now d8 may support android 8 below devices too

### PR DESCRIPTION
**Pull request by SaiKiranSparkApps**
D8 may now support android 8 below devices too

### CODE REVIEW

**Comment by khaled-0** [comment]
That build.gradle is only for Sketchware app
It doesn't affect projects

**Comment by SaiKiranSparkApps** [comment]
No bro it backports d8 code & makes d8 supported for below android 8

**Comment by SaiKiranSparkApps** [comment]
Why don't you try it

**Comment by SaiKiranSparkApps** [comment]
It will for sure effects on project

**Comment by JavkhlanK** [comment]
aight I'mma try that out, but it probably won't work, as d8/r8 use `java.nio` APIs, and I'm not sure if any official desugar tools exist for them already.

**Comment by SaiKiranSparkApps** [comment]
https://maven.google.com/web/m_index.html?q=desugar#com.android.tools:desugar_jdk_libs:1.1.5
It is the official desugar library from maven.google.com & latest version too

**Comment by JavkhlanK** [comment]
aight I tested the main parts of this PR out and it's not working for d8, sadly.

gnome-shell-screenshot-RGJV60

**Pull request closed without merging**
