### PR TITLE
Firebase without Appcompat

### PR DESCRIPTION
**Pull request by Did-Dog**
A main problem in sketchware ,can't use firebase without approbation.
I removed the connection of appcompat and firebase.Now we can use firebase without approbation.

### CODE REVIEW

**Comment by PranavPurwar** [comment]
i think it already works without that, I've used firebase without appcompat in many projects (earlier)

**Comment by ilyassesalama** [comment]
This is interesting, needs a detailed test though.

**Comment by Did-Dog** [comment]
> This is interesting, needs a detailed test though.

**Comment by Did-Dog** [comment]
> > This is interesting, needs a detailed test though.
How can I compile Sketchware Pro's source into an APK file

**Comment by PranavPurwar** [comment]
clonr the repository on android studio, click Sync Gradle and click run/debug

**Comment by Did-Dog** [comment]
> clonr the repository on android studio, click Sync Gradle and click run/debug

Ok

**Comment by PranavPurwar** [comment]
or if you're in mobile ->
add this code to android config in bulid.gradle and test 

jackOptions {
      enabled true
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

**Comment by JavkhlanK** [comment]
That looks like an interesting change, I'll test that out soon as well. By the way, you should rather remove code entirely instead of commenting it out, as the entire history (including the old unchanged version) is available thanks to Git.

**Comment by JavkhlanK** [comment]
Unfortunately, Sketchware didn't lie that Firebase depends on AppCompat. Looking at the dependencies of just `com.google.firebase:firebase-common:19.0.0` (exactly the version built-in Sketchware Pro), you can find `com.google.android.gms:play-services-basement:17.0.0` which depends on various AppCompat (AndroidX, actually) libraries, so not including them in the APK is **not safe**.

**Pull request closed without merging**
