### PR TITLE
feat: significantly reduce the app size

### PR DESCRIPTION
**Pull request by Lohita9**
These changes do not involve any modifications to method names, field names, or class names in the APK file.

### CODE REVIEW

**Comment by trindadedev13** [comment]
can you give an apk  with this change?

**Comment by ilyassesalama** [comment]
I bet that you didn't even test your changes. Sketchware Pro still needs some code cleanup in order for what you've done to work.

**Comment by ilyassesalama** [comment]
> I understand your concern, and you're right—I didn't test the changes in the forked repo because the latest commit of the Sketchware Pro APK build is failing.

You should test on your machine, not on our GitHub Actions.

**Comment by PranavPurwar** [comment]
Resource obfuscation and minification does not work with Sketchware Pro.

**Pull request closed without merging**
