### PR TITLE
feat: Add Kotlin Compiler

### PR DESCRIPTION
**Pull request by SaiKiranSparkApps**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
btw the commit messages should be similar to `feat: Add Kotlin compiler`, too

**Comment by SaiKiranSparkApps** [comment]
K i am changing title

**Comment by JavkhlanK** [comment]
wait no, the title is fine, it's the commit messages you make which are wrong

**Comment by SaiKiranSparkApps** [comment]
If i need to update any changes comment

**Comment by leapofazzam123** [comment]
Why closed

**Comment by leapofazzam123** [comment]
For no apperent reason

**Comment by SaiKiranSparkApps** [comment]
Kotlin Compiler uses some classes that don't support on Android.
So it is currently closed

**Comment by SaiKiranSparkApps** [comment]
But i will try to bring it back

**Pull request closed without merging**
