### PR TITLE
fix: Check for storage perms before reading config

### PR DESCRIPTION
**Pull request by khaled-0**
If no storage perms , don't try to read for custom config,
Fixes startup crash

### CODE REVIEW

**Comment by JavkhlanK** [comment]
I think changing ConfigActivity's logic to not try to read Mod Settings if no storage permissions have been granted and/or handle `null` HashMaps correctly would be a better solution.

**Comment by khaled-0** [comment]
> I think changing ConfigActivity's logic to not try to read Mod Settings if no storage permissions have been granted and/or handle `null` HashMaps correctly would be a better solution.

cant check for perms without passing context, which seems unnecessary if ,
lets try to handle null then

**Comment by khaled-0** [comment]
Ha, much better now

**Comment by JavkhlanK** [comment]
> > I think changing ConfigActivity's logic to not try to read Mod Settings if no storage permissions have been granted and/or handle `null` HashMaps correctly would be a better solution.
> 
> cant check for perms without passing context, which seems unnecessary if ,
> lets try to handle null then

It'd be possible to use `SketchApplication#getContext()` for a Context.

**Comment by khaled-0** [comment]
> > > I think changing ConfigActivity's logic to not try to read Mod Settings if no storage permissions have been granted and/or handle `null` HashMaps correctly would be a better solution.
> > 
> > 
> > cant check for perms without passing context, which seems unnecessary if ,
> > lets try to handle null then
> 
> It'd be possible to use `SketchApplication#getContext()` for a Context.

Not necessary anymore , because null check serves the purpose.

**Pull request merged**
