### PR TITLE
Update KotlinCompilerBridge.java

### PR DESCRIPTION
**Pull request by aladinim**
I am checking this in every device. So the Kotlin was working well on v27 but now it stopped. Because of HeyStudio's idea i guess.

### CODE REVIEW

**Review by aladinim — COMMENTED** [review]
,

**Comment by JavkhlanK** [comment]
I'm not sure what this is supposed to do, but thanks for making me notice how that useless method & its checks are.

**Comment by MikeAndrson** [comment]
Got referred to as "Hey Studios" after so much time 🥲 Really takes you back

**Comment by MikeAndrson** [comment]
Also yeah those are redundant since kt feature is on a different flavor anyway

**Pull request closed without merging**
