### PR TITLE
feat, fix: add space in delete file dialog's content

### PR DESCRIPTION
**Pull request by PranavPurwar**

### CODE REVIEW

**Comment by JavkhlanK** [comment]
won't that add a double space to manifest items?

**Comment by PranavPurwar** [comment]
Screenshot_2021-09-21-21-58-56
see this when

**Comment by JavkhlanK** [comment]
Now try to delete a Java file that got added to the manifest with your change.
Anyway, I got what you wanted you fix and fixed it myself with 925f2a0d3e65b7b54e5aecbdac018ec2b6c66dd6
Thanks for reporting that issue!

**Comment by PranavPurwar** [comment]
ok

**Pull request closed without merging**
