### PR TITLE
refactor, feat: ViewEditor, Nx, Ox, Lx.

### PR DESCRIPTION
**Pull request by AlucardTN**
- feat: add Nx.
- feat: add ViewEditor and inline some of he's classes
- refactor: some Integer values changed to hex in Ox
- refactor: some libraries text changed to stable when exporting project to AS in Lx (because Sketchware use Glide and OkHttp3 4.11.0 and when exporting your project to android studio version 4.12.0 from both OkHttp3 and Glide can cause missing imports...)

- change tested and they are working well

### CODE REVIEW

**Comment by AlucardTN** [comment]
image
in Ox you can see that i'm using LF and only converted 2 integers to hex value (0xffffff)

**Comment by JavkhlanK** [comment]
Just a question: Why did you downgrade Glide's version in an exported project to 4.11.0? 4.12.0 is already available.

**Comment by JavkhlanK** [comment]
Same thing for OkHttp3

**Comment by AlucardTN** [comment]
because Sketchware use Glide and OkHttp3 4.11.0 and when exporting your project to android studio version 4.12.0 from both OkHttp3 and Glide can cause missing imports...

**Comment by JavkhlanK** [comment]
Alright, just a small note about it in the PR comment would've been nice.

**Comment by AlucardTN** [comment]
yeah, i'll edit it now

**Comment by AlucardTN** [comment]
means i'll edit the PR first comment !

**Comment by AlucardTN** [comment]
me waiting for this to get accepted

**Comment by Iyxan23** [comment]
when the

**Comment by JavkhlanK** [comment]
smae

**Pull request merged**
