### PR TITLE
feat: upgrade to sora-editor 0.20.4

### PR DESCRIPTION
**Pull request by NiceSapien**

### CODE REVIEW

**Comment by NiceSapien** [comment]
the commit message was longer than the change lol

**Comment by hasrat-ali** [comment]
Bruh

**Comment by NiceSapien** [comment]
damas no work

**Comment by JavkhlanK** [comment]
Gotta test branch protection rules

**Comment by JavkhlanK** [comment]
Nice, they work:  
Screenshot_20221230_161849_Firefox Nightly

**Pull request closed without merging**
