### PR TITLE
[WIP] UI fixes

### PR DESCRIPTION
**Pull request by remaker17**
Description is empty.

## Summary by CodeRabbit

- **New Features**
	- Enhanced theme setting for the main activity interface.
	- Updated navigation drawer to improve user interaction.
	- Implemented Edge-to-Edge support in library management screens for a more immersive experience.
	- Added back handling in Log Reader Activity for better navigation control.
- **Refactor**
	- Updated various activities and fragments to use new UI components for consistency and better performance.
	- Simplified UI management in tools and resource activities by removing outdated color references.
- **Chores**
	- Updated `.gitignore` to support Android IDE project files.
- **Style**
	- Adjusted widget text size and orientation for better readability and alignment.
- **Bug Fixes**
	- Fixed visibility issues in custom attribute management screens.
- **Documentation**
	- Removed outdated button styles references from public stable IDs documentation.

### CODE REVIEW

**Comment by TheRemakerMan** [comment]
Can you fast merge it?
I want to make new changes.

**Comment by ilyassesalama** [comment]
The LogReaderActivity is broken though, why the search and bottom sheet are showing even if there are no logs shown? Also, that bottom sheet is still in question, it doesn’t look very good IMO, it’s so compact.

**Comment by TheRemakerMan** [comment]
> The LogReaderActivity is broken though, why the search and bottom sheet are showing even if there are no logs shown? Also, that bottom sheet is still in question, it doesn’t look very good IMO, it’s so compact.

Okay

**Comment by remaker17** [comment]
@ilyassesalama

**Comment by ilyassesalama** [comment]
> The LogReaderActivity is broken though, why the search and bottom sheet are showing even if there are no logs shown? Also, that bottom sheet is still in question, it doesn’t look very good IMO, it’s so compact.

Can you please fix these issues so I can merge this PR.

**Comment by remaker17** [comment]
> > The LogReaderActivity is broken though, why the search and bottom sheet are showing even if there are no logs shown? Also, that bottom sheet is still in question, it doesn’t look very good IMO, it’s so compact.
> 
> Can you please fix these issues so I can merge this PR.

Nope, I can't fix these issues, cause I'm busy.

**Comment by hasrat-ali** [comment]
@coderabbitai review

**Pull request merged**
