### PR TITLE
feat: Improve AboutModActivity

### PR DESCRIPTION
**Pull request by JavkhlanK**
This makes some important fixes to AboutModActivity. Opened a PR because I wasn't sure of the ripple effects, but maybe y'all have more to comment on.

### CODE REVIEW

**Comment by khaled-0** [comment]
Woaw that was really cool👍

**Comment by ilyassesalama** [comment]
Ripple color doesn't look good, can you try #E8E8E8 instead of #848484?

**Comment by remakerofficial** [comment]
Why not use for ripple color `#1F000000`?

**Comment by JavkhlanK** [comment]
Any comments now?

**Comment by ilyassesalama** [comment]
Looks good so far, you can merge that.

**Comment by PlayCodeee** [comment]
Really Coll

**Pull request merged**
