### PR TITLE
Update SrcCodeEditor.java

### PR DESCRIPTION
**Pull request by Arashvscode**
New feature!
Adjust the keyboard screen for better writing. For more understanding, pay attention to the image below. Icons will be added soon for better coding.
Screenshot_۲۰۲۲۰۴۲۸-۱۷۰۱۵۲_vs code mobile
As you can see in the picture, the keyboard is connected to the screen

### CODE REVIEW

**Comment by Arashvscode** [comment]
Strange, this code works well for me

**Comment by khaled-0** [comment]
Remove the `` د``
From line 359 
Screenshot_20220429-144233274

**Comment by khaled-0** [comment]
And rename your pull request title to something like
``misc: Auto resize code editor when keyboard is visible ``

**Comment by khaled-0** [comment]
And is the tryCatch necessary?
Remove the tryCatch if you may

**Comment by Arashvscode** [comment]
> 

Yes it is necessary if I delete it it may not work well or even the program may jump I have tried before without try and it gave me an error

**Comment by JavkhlanK** [comment]
Since it still looks like you didn't test out your changes, I'll close this. We won't accept not tested out changes.

**Pull request closed without merging**
