### PR TITLE
aapt1_appt2

### PR DESCRIPTION
**Pull request by PHANTOMLOCAL**

### CODE REVIEW

**Comment by Amirtah90** [comment]
F

**Comment by ro681** [comment]
### 

> _****_

**Comment by ro681** [comment]
Rohit Vishwakarama

**Comment by ro681** [comment]
Rohit Vishwakarama ### 

> ### ### ### ### ### **__**

**Comment by ro681** [comment]
### 

> 

>

**Comment by herickreis889-ops** [comment]
Oi

**Comment by ntaoliveira201017-eng** [comment]
Mdss

**Comment by ntaoliveira201017-eng** [comment]
https://github.com/ntaoliveira201017-eng/Natan.git

**Pull request closed without merging**
