### PR TITLE
Wip deobfuscation

### PR DESCRIPTION
**Pull request by hasrat-ali**

### CODE REVIEW

**Comment by hasrat-ali** [comment]
Gonna merge with command line

**Comment by JavkhlanK** [comment]
I think just a single commit with the latest .jar files would be best without having tons of slightly changed .jar files blowing up the repository's size.

**Comment by hasrat-ali** [comment]
😔 
>I don't really like commits touching a lot of files, and neither too small ones. I only touched some of those ~~layouts~~ as I got to them while refactoring other files.
https://github.com/Sketchware-Pro/Sketchware-Pro/commit/c05b221662cae7adada55f075c1571c7d030ca65#commitcomment-81628470

**Comment by JavkhlanK** [comment]
That'd exclude squashes, multiple commits put together into a single one

**Comment by JavkhlanK** [comment]
pensive

**Pull request closed without merging**
