### PR TITLE
add android ci

### PR DESCRIPTION
**Pull request by PranavPurwar**

### CODE REVIEW

**Comment by khaled-0** [comment]
Description 😔
Title 😔

**Comment by khaled-0** [comment]
feat,misc: Add GitHub workflow integration to auto generate latest apk

Idk description 😔

**Comment by ilyassesalama** [comment]
I bet the compilation will fail. Android CI in Sketchware Pro repository is useless.

**Comment by JavkhlanK** [comment]
Why would compilation fail? Looks like it would do the same as building a debug APK with Android Studio.

And about it being useless, contribution would be possible without needing to own a desktop with Gradle + the Android SDK on it, which would enable (easy) pure mobile-only development again.

**Comment by ilyassesalama** [comment]
Fair enough.

**Comment by PranavPurwar** [comment]
> I bet the compilation will fail. Android CI in Sketchware Pro repository is useless.

gimme $1 if you lose the bet 😳

**Comment by khaled-0** [comment]
Ha

**Comment by PranavPurwar** [comment]
shut up

**Pull request closed without merging**
