### PR TITLE
feat: add visibility property

### PR DESCRIPTION
**Pull request by trindadedev13**
https://t.me/sketchwarepro/223903/270070

Why draft?
i'll make another PR before finish this...

### CODE REVIEW

**Comment by elfilibusterismo** [comment]
Is this really necessary? How would the user make changes to it when visibility is gone? By looking to the list of views or something? Isn't that a bad idea? What if I only have one widget and set visibility gone? How would I select it?

**Comment by elfilibusterismo** [comment]
No more introducing another variable in ViewBean if it's only for adding a property for preview; use custom attributes (inject property) instead.

**Comment by trindadedev13** [comment]
> No more introducing another variable in ViewBean if it's only for adding a property for preview; use custom attributes (inject property) instead.

bruh, users will have to use inject bruhhhhhhhh

**Comment by elfilibusterismo** [comment]
> > No more introducing another variable in ViewBean if it's only for adding a property for preview; use custom attributes (inject property) instead.
> 
> bruh, users will have to use inject bruhhhhhhhh but okay, i"ll close again then 🥷

I literally just added a way for much easier for users to add an attributes in inject property

**Comment by trindadedev13** [comment]
> > > No more introducing another variable in ViewBean if it's only for adding a property for preview; use custom attributes (inject property) instead.
> > 
> > 
> > bruh, users will have to use inject bruhhhhhhhh but okay, i"ll close again then 🥷
> 
> I literally just added a way for much easier for users to add an attributes in inject property

Yes

**Pull request closed without merging**
