### PR TITLE
feat: add members Github url in host

### PR DESCRIPTION
**Pull request by aquilesTrindade**

### CODE REVIEW

**Comment by remaker17** [comment]
Hello, I have a question about this PR. Why did you need to add this?

**Comment by aquilesTrindade** [comment]
> Olá, tenho uma pergunta sobre este PR. Por que você precisou adicionar isso?

Hello, there is no specific reason, I just had the idea and wanted to do it

**Comment by PranavPurwar** [comment]
> > Olá, tenho uma pergunta sobre este PR. Por que você precisou adicionar isso?
> 
> Hello, there is no specific reason, I just had the idea and wanted to do it

What's the point of it? Without changes in sketchware pro, these changes are useless

**Comment by aquilesTrindade** [comment]
> > > Olá, tenho uma pergunta sobre este PR. Por que você precisou adicionar isso?
> > 
> > 
> > Olá, não há um motivo específico, eu apenas tive a ideia e quis fazê-la
> 
> Qual é o sentido disso? Sem mudanças no Sketchware Pro, essas mudanças são inúteis

so close them, simple.

**Comment by aquilesTrindade** [comment]
tell me, why in this theoretically "useless" PR you talk and look, now in the pr https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1192
you don't speak, don't requestao changes, or anything related?

**Comment by PranavPurwar** [comment]
> tell me, why in this theoretically "useless" PR you talk and look, now in the pr #1192 you don't speak, don't requestao changes, or anything related?

remaker already pointed out issues in that PR

**Comment by aquilesTrindade** [comment]
> > tell me, why in this theoretically "useless" PR you talk and look, now in the pr #1192 you don't speak, don't requestao changes, or anything related?
> 
> remaker already pointed out issues in that PR

Yes, after I said it.

**Comment by HanzoDev1375** [comment]
مردم قبل از استفاده از api های github

**Comment by aquilesTrindade** [comment]
> Por favor, não use esta API no github

nowhere does it have an api.

**Comment by aquilesTrindade** [comment]
> مردم قبل از استفاده از api های github

it doesn't have any api.

**Comment by HanzoDev1375** [comment]
> > مردم قبل از استفاده از api های github
> 
> it doesn't have any api.

public static String DevList = "https://api.github.com/repos/HanzoDev1375/Ghostide/contributors";

مخزن خودتان را قالب کنید

**Comment by HanzoDev1375** [comment]
اشاره به همسر اینده خودم یعنی 
@JavkhlanK 
عشق منی تو

**Comment by JavkhlanK** [comment]
bro wtf is this weird drama

**Comment by remaker17** [comment]
LMAO

**Comment by aquilesTrindade** [comment]
ok❤️

**Comment by aquilesTrindade** [comment]
> bro wtf is this weird drama

❤️

**Pull request closed without merging**
