### PR TITLE
Update SrcCodeEditor.java

### PR DESCRIPTION
**Pull request by Arashvscode**
Screenshot_۲۰۲۲۰۴۲۳-۱۹۰۱۱۶_vs code mobile(beta)
Adjust the command line to get better code and more beautiful reading

### CODE REVIEW

**Comment by Arashvscode** [comment]
Look at the white lines

**Comment by JavkhlanK** [comment]
Not sure if everyone would like that. Adding that as setting would be better.

**Comment by Arashvscode** [comment]
> Not sure if everyone would like that. Adding that as setting would be better.

No, it 's beautiful. 99% favorite. If not, add an option

**Comment by khaled-0** [comment]
Bro don't add this.
This looks like shit.😐

**Comment by Arashvscode** [comment]
> 

What is my title and then you can add it to the menu

**Comment by JavkhlanK** [comment]
Looks like #369 is an improved version of this. Please update your old Pull requests instead of opening new ones, or even if you do, close the old ones.

**Comment by Arashvscode** [comment]
This feature does not work without manual activation. I close the pull

**Comment by Arashvscode** [comment]
> 
Excuse me, I will do the same in the future

**Pull request closed without merging**
