### PR TITLE
Added Archived Team and Myself

### PR DESCRIPTION
**Pull request by NiceSapien**
@ilyassesalama

### CODE REVIEW

**Comment by PranavPurwar** [comment]
Where is the PR adding archived team in about screen?

**Comment by NiceSapien** [comment]
> Where is the PR adding archived team in about screen?

Which about screen? The app's? It'll be done in the website, and please check discord too. Ilyasse told me to create a new array.

**Comment by PranavPurwar** [comment]
Also no use because it will be overwritten by the CI

**Comment by NiceSapien** [comment]
atleast the archived team will remain

**Comment by PranavPurwar** [comment]
> > Where is the PR adding archived team in about screen?
> 
> Which about screen? The app's? It'll be done in the website, and please check discord too. Ilyasse told me to create a new array.

Why not give the due credit in the app aswell?

**Comment by NiceSapien** [comment]
> > > Where is the PR adding archived team in about screen?
> > 
> > 
> > Which about screen? The app's? It'll be done in the website, and please check discord too. Ilyasse told me to create a new array.
> 
> Why not give the due credit in the app aswell?

It's your job to work on the app. Do it then. Merge both the arrays. I made a new array so it doesn't get overwritten by the CI.

**Pull request merged**
