### PR TITLE
Feat: icon maker + some fixes

### PR DESCRIPTION
**Pull request by Mustiy0**
for some reason my old already accepted commits attached with this pull idk how to remove them.

### CODE REVIEW

**Comment by laymintu** [comment]
Can you make an adaptive logo? Please make for us 🙏🥺

**Comment by Mustiy0** [comment]
> Can you make an adaptive logo? Please make for us 🙏🥺

It's already there

**Comment by RoyTheReal** [comment]
The adaptive icon toggle doesn't seem to do anything... You can't upload a foreground, background, and monochrome

**Comment by Mustiy0** [comment]
Yes monochrome and foreground are auto created
Check mipmaps folder after creating an icon just make sure to check adaptive-icon toggle

**Pull request merged**
