### PR TITLE
feat: allow reporting error directly to discord

### PR DESCRIPTION
**Pull request by PranavPurwar**
when the application crashes a dialog will ask user if he wants to report the error. If user clicks "report" the error will be sent through webhook to the modder team

IMPORTANT: You need to put your webhook url in the variable "webUrl" present in com/besome/sketch/tools/CollectErrorActivity
Please make sure to encrypt it so that it doesn't get leaked!

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Why did you replace RequestNetwork.java and RequestNetworkController.java? They were working & formatted properly already.

**Comment by khaled-0** [comment]
Imagine the number of spams this can lead to  :piola:

**Comment by PranavPurwar** [comment]
no way

**Comment by PranavPurwar** [comment]
not much crashes are reported in beta, and noone would crash skpro and report it again and again just to spam so that spam thing is kinda impossible to happen

**Comment by PranavPurwar** [comment]
you guys even want to merge this pr ? if not, then tell me and i will close it myself

**Comment by khaled-0** [comment]
> you guys even want to merge this pr ? if not, then tell me and i will close it myself

Just ignore bruh , why close
Another one is open for almost 3months now

**Pull request closed without merging**
