### PR TITLE
update aapt2 for arm

### PR DESCRIPTION
**Pull request by TheRemakerMan**
I took aapt2 from @lzhiyong's [android-sdk-tools](https://github.com/lzhiyong/android-sdk-tools) repository.

### CODE REVIEW

**Comment by JavkhlanK** [comment]
Can Sketchware Pro just use that aapt2 binary or have you already asked for permission? The app's repo is GPL-3.0-licensed, while Sketchware Pro isn't.

**Comment by guhg** [comment]
Sketchware needs to run the newest version of aapt2.

**Comment by TechnicalStudioDeveloper** [comment]
> Can Sketchware Pro just use that aapt2 binary or have you already asked for permission? The app's repo is GPL-3.0-licensed, while Sketchware Pro isn't.

https://github.com/AndroidIDEOfficial/AndroidIDE/issues/981

**Comment by JavkhlanK** [comment]
for more info, see [this repo's LICENSE file](https://github.com/Sketchware-Pro/Sketchware-Pro/blob/662acf62c2a4d8d29b3f04ead06412c4a2ef79a6/LICENSE).

**Comment by PranavPurwar** [comment]
my dear @JavkhlanK bro swpro is already illegal

**Comment by JavkhlanK** [comment]
So what? Shadily relicensing the entire codebase to GPLv3 will just confuse others by lying to them about the code being open source, all on top of it having been decompiled already.

**Comment by TheRemakerMan** [comment]
Then you need to add license for aapt2 file like these modules.

**Pull request closed without merging**
