### PR TITLE
Redesign aB dialog

### PR DESCRIPTION
**Pull request by TheRemakerMan**

### CODE REVIEW

**Comment by TheRemakerMan** [comment]
sorry for late pr, i was busy :pensive:

**Comment by JavkhlanK** [comment]
and it already has conflicts. can you fix them?

**Comment by TheRemakerMan** [comment]
> and it already has conflicts. can you fix them?

how? i cannot fix merge conflicts
Screenshot_20230916-143828

**Comment by JavkhlanK** [comment]
you can and mostly should resolve conflicts locally using your IDE, not using the web interface since it sucks

**Comment by JavkhlanK** [comment]
a cleaner way to fix the conflicts would've probably been rebasing your local `material-redesign` branch on `origin/material-redesign`

**Comment by TheRemakerMan** [comment]
Bruh, again merge conflicts

**Comment by ilyassesalama** [comment]
Why did you close it though? I was testing your PR to merge it.

**Comment by ilyassesalama** [comment]
Everything looks good to me.

**Pull request merged**
